name: Backend CI Test to develop

on:
  pull_request:
    branches:
      - develop
    paths:
      - "backend/**"

env:
  SPRING_PROFILE: test
  DB_URL: jdbc:mysql://localhost:3306/todoc_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  DB_USERNAME: root
  DB_PASSWORD: deokwon11@

jobs:
  validate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: todoc_db
          MYSQL_ROOT_PASSWORD: deokwon11@
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -pdeokwon11@ || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=30
          --health-start-period=20s

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Gradle
        run: |
          cd backend/server
          ./gradlew test