name: Backend CI Test to develop

on:
  pull_request:
    branches:
      - develop
    paths:
      - "backend/**"

env:
  SPRING_PROFILE: ci

concurrency:
  group: ci-${{ github.ref }}-backend
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17 (Temurin) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Run tests
        working-directory: backend/server
        env:
          SPRING_PROFILES_ACTIVE: ci
          # Gradle 빌드/테스트 가속 옵션
          GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false
        run: |
          ./gradlew clean test --no-daemon --info --stacktrace
